name: Base Images

on:
  push:
    branches: 
      - main
    paths:
      - oses/**
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"


jobs:
  push:
    name: "base-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - alpine
          - debian
          - ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debugging
        run: |
          ls -ltr .
        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./oses/${{ matrix.version }}
          file: ./oses/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/aleforge/base:${{ matrix.version }}
