name: Java

on:
  push:
    branches: 
      - main
    paths:
      - Java/temurin/**
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"


jobs:
  push:
    name: "AleForge-Java-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - 8
          - 11
          - 16
          - 17
          - 19
          - 21
          - 23
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Java
          file: ./Java/temurin/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/aleforge/containers:java-${{ matrix.version }}
