name: MariaDB Image

on:
  push:
    branches:
      - main
    paths:
      - mariadb/**
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  push:
    name: "MariaDB-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - "10.3"
          - "10.4"
          - "10.5"
          - "10.6"
          - "10.7"
          - "11.2"
          - "11.3"
          - "11.4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debugging
        run: |
          ls -ltr .
        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mariadb/
          file: ./mariadb/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/aleforge/mariadb:${{ matrix.version }}
