name: build steamcmd

on:
  push:
    branches: 
      - main
    paths:
      - steamcmd/**
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  push:
    name: "AleForge-${{ matrix.version }}"
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    strategy:
        fail-fast: false
        matrix:
            version:
            - debian
            - dotnet
            - proton
            - ubuntu
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Debugging
      run: |
        ls -ltr .
      shell: bash
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./steamcmd/${{ matrix.version }}
        file: ./steamcmd/${{ matrix.version }}/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
            ghcr.io/aleforge/steamcmd:${{ matrix.version }}