name: Wine
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - wine/**
jobs:
  push:
    name: "Wine ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - devel
          - staging
          - 7
          - 8
          - 9
          - 10
    steps:
        - uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./wine
            file: ./wine/${{ matrix.tag }}/Dockerfile
            platforms: linux/amd64
            push: true
            tags: |
                ghcr.io/aleforge/wine:${{ matrix.tag }}