name: Wine
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - wine/**
jobs:
  push:
    name: "aleforge:wine_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
          - devel
          - staging
          - 8
    steps:
        - uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Debugging
          run: |
            ls -ltr .
            shell: bash
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./wine
            file: ./wine/${{ matrix.tag }}/Dockerfile
            platforms: linux/amd64
            push: true
            tags: |
                ghcr.io/aleforge/wine:${{ matrix.tag }}